//! Port of electron/services/excel.service.js — directory import template,
//! strict workbook parsing (type-specific and legacy layouts), and inventory
//! export, built on umya-spreadsheet (pure Rust, no ExcelJS/Node).
//!
//! Every validation rule, column set and error message matches the Electron
//! build so previously distributed workbooks keep importing unchanged.

use crate::db::AppDatabase;
use serde_json::{json, Value};
use crate::error::{AppError, AppResult};
use umya_spreadsheet::{
    Alignment, Border, BorderStyleValues, Color, Coordinate, DataValidation, DataValidationOperatorValues,
    DataValidationValues, DataValidations, HorizontalAlignmentValues, Pane, PaneStateValues, PaneValues, PatternFill,
    PatternValues, SheetView, Style, VerticalAlignmentValues,
};

const DEVICE_TYPES: [&str; 10] = ["Router", "Switch", "iLO", "Server", "NVR", "AccessPoint", "Scale", "Client", "Checkout", "POS"];
pub const MAX_SWITCH_PORTS: usize = 48;

const BRANCH_HEADERS: [&str; 11] = [
    "Branch Name", "Branch Code", "Warehouse Code", "Link1", "IP Link1", "Link2", "IP Link2",
    "Manager Name", "Manager Tell", "Deputy Name", "Deputy Tell",
];
/// Retained for importing workbooks generated by earlier application versions.
const LEGACY_BRANCH_HEADERS: [&str; 11] = [
    "Name", "Code", "Warehouse Code", "Link1", "IP Link1", "Link2", "IP Link2",
    "Manager Name", "Manager Tell", "Deputy Name", "Deputy Tell",
];
const LEGACY_DEVICE_HEADERS: [&str; 21] = [
    "Branch Code", "Device Type", "Device Name", "Model", "Location", "IP", "Port", "Asset Code",
    "Connection Type", "Connection Port", "Hostname", "User", "Domain", "ESXI Version",
    "Software Version", "Terminal ID", "Acceptance ID", "Brand", "Checkout Number",
    "Serial Number", "Dashboard",
];
const PORT_HEADERS: [&str; 8] = ["Branch Code", "Device Name", "Device IP", "Port Number", "VLAN", "Status", "IP", "Details"];

/// The canonical value is the legacy Devices-sheet heading used by the parser's
/// common field map. Each equipment sheet exposes only fields available in its UI form.
const DEVICE_SHEET_FIELDS: &[(&str, &[(&str, &str)])] = &[
    ("Router", &[("Device Name", "name"), ("Model", "model"), ("IP", "ip"), ("Port", "port"), ("Asset Code", "asset_code")]),
    (
        "Switch",
        &[
            ("Device Name", "name"),
            ("Model", "model"),
            ("Location", "location"),
            ("IP", "ip"),
            ("Connection Type", "connection_type"),
            ("Connection Port", "connection_port"),
            ("Asset Code", "asset_code"),
        ],
    ),
    ("iLO", &[("Device Name", "name"), ("IP", "ip"), ("ESXI Version", "esxi_version"), ("Server Model", "model"), ("Asset Code", "asset_code")]),
    ("Server", &[("Device Name", "name"), ("Hostname", "hostname"), ("IP", "ip")]),
    ("NVR", &[("Device Name", "name"), ("IP", "ip"), ("Model", "model"), ("Asset Code", "asset_code")]),
    (
        "AccessPoint",
        &[("Device Name", "name"), ("Model", "model"), ("Location", "location"), ("IP", "ip"), ("Port", "port"), ("Asset Code", "asset_code")],
    ),
    (
        "Scale",
        &[("Device Name", "name"), ("Model", "model"), ("Location", "location"), ("IP", "ip"), ("Serial Number", "serial_number"), ("Asset Code", "asset_code")],
    ),
    ("Client", &[("Device Name", "name"), ("Hostname", "hostname"), ("User", "user"), ("IP", "ip"), ("Domain", "domain")]),
    ("Checkout", &[("Device Name", "name"), ("Checkout Number", "checkout_number"), ("Hostname", "hostname"), ("IP", "ip")]),
    (
        "POS",
        &[
            ("Device Name", "name"),
            ("Checkout Number", "checkout_number"),
            ("Brand", "brand"),
            ("Model", "model"),
            ("Software Version", "version"),
            ("IP", "ip"),
            ("Terminal ID", "terminal_id"),
            ("Acceptance ID", "acceptance_id"),
            ("Asset Code", "asset_code"),
        ],
    ),
];

const FIELD_MAP: &[(&str, &str)] = &[
    ("Device Name", "name"),
    ("Model", "model"),
    ("Location", "location"),
    ("IP", "ip"),
    ("Port", "port"),
    ("Asset Code", "asset_code"),
    ("Connection Type", "connection_type"),
    ("Connection Port", "connection_port"),
    ("Hostname", "hostname"),
    ("User", "user"),
    ("Domain", "domain"),
    ("ESXI Version", "esxi_version"),
    ("Software Version", "version"),
    ("Terminal ID", "terminal_id"),
    ("Acceptance ID", "acceptance_id"),
    ("Brand", "brand"),
    ("Checkout Number", "checkout_number"),
    ("Serial Number", "serial_number"),
];

pub fn device_types() -> &'static [&'static str; 10] {
    &DEVICE_TYPES
}

/// Port of `clean()` — a filter value shaped into a safe filename fragment.
pub fn excel_clean(value: &str) -> String {
    let pattern = regex::Regex::new(r"[^a-z0-9_-]").expect("static regex");
    let text = if value.is_empty() { "All" } else { value };
    pattern.replace_all(text, "_").to_string()
}

fn sheet_fields(type_name: &str) -> &'static [(&'static str, &'static str)] {
    DEVICE_SHEET_FIELDS.iter().find(|(kind, _)| *kind == type_name).map(|(_, fields)| *fields).unwrap_or(&[])
}

fn switch_port_header(group: usize, suffix: &str) -> String {
    format!("Port {group} {suffix}")
}

fn device_sheet_headers(type_name: &str) -> Vec<String> {
    let mut headers: Vec<String> = vec!["Branch Code".into()];
    for (header, _) in sheet_fields(type_name) {
        headers.push((*header).into());
    }
    headers.push("Dashboard".into());
    if type_name == "Switch" {
        for group in 1..=MAX_SWITCH_PORTS {
            for suffix in ["Number", "VLAN", "Status", "IP", "Details"] {
                headers.push(switch_port_header(group, suffix));
            }
        }
    }
    headers
}

fn column_letter(index: u32) -> String {
    // 1-based column index → spreadsheet letters.
    let mut index = index;
    let mut letters = Vec::new();
    while index > 0 {
        let remainder = ((index - 1) % 26) as u8;
        letters.push((b'A' + remainder) as char);
        index = (index - 1) / 26;
    }
    letters.reverse();
    letters.into_iter().collect()
}

fn width_for(header: &str) -> f64 {
    if header.contains("Details") {
        24.0
    } else if header.ends_with("Status") || header == "Dashboard" {
        13.0
    } else if header == "Branch Code" || header == "Device Name" || header == "Hostname" || header == "Model" || header == "Location" || header.starts_with("Asset") {
        20.0
    } else {
        16.0
    }
}

fn header_color(argb: &str) -> Color {
    let mut color = Color::default();
    color.set_argb_str(argb);
    color
}

fn header_style() -> Style {
    let mut style = Style::default();
    let font = style.font_mut();
    font.set_bold(true);
    font.set_color(header_color("FFFFFFFF"));
    let pattern: &mut PatternFill = style.fill_mut().pattern_fill_mut();
    pattern.set_pattern_type(PatternValues::Solid);
    pattern.set_foreground_color(header_color("FF5E81AC"));
    let mut alignment = Alignment::default();
    alignment.set_vertical(VerticalAlignmentValues::Center);
    alignment.set_horizontal(HorizontalAlignmentValues::Center);
    alignment.set_wrap_text(true);
    style.set_alignment(alignment);
    let mut border = Border::default();
    border.set_style(BorderStyleValues::Thin);
    border.set_color(header_color("FF4C566A"));
    style.borders_mut().set_bottom(border);
    style
}

fn freeze_top_row(worksheet: &mut umya_spreadsheet::Worksheet) {
    let mut coordinate = Coordinate::default();
    coordinate.set_col_num(3);
    coordinate.set_row_num(2);
    let mut pane = Pane::default();
    pane.set_vertical_split(2.0);
    pane.set_horizontal_split(1.0);
    pane.set_top_left_cell(coordinate);
    pane.set_state(PaneStateValues::Frozen);
    pane.set_active_pane(PaneValues::BottomRight);
    let views = worksheet.sheet_views_mut();
    if views.sheet_view_list_mut().is_empty() {
        views.add_sheet_view_list_mut(SheetView::default());
    }
    if let Some(view) = views.sheet_view_list_mut().first_mut() {
        view.set_pane(pane);
    }
}

fn style_sheet(worksheet: &mut umya_spreadsheet::Worksheet, headers: &[String]) {
    freeze_top_row(worksheet);
    let last_column = column_letter(headers.len() as u32);
    worksheet.set_auto_filter(format!("A1:{last_column}1"));
    worksheet.row_dimension_mut(1).set_height(28.0);
    for (index, header) in headers.iter().enumerate() {
        let letter = column_letter(index as u32 + 1);
        {
            let cell = worksheet.cell_mut(format!("{letter}1").as_str());
            cell.set_value(header.as_str());
            let style = header_style();
            cell.set_style(style);
        }
        worksheet.column_dimension_mut(&letter).set_width(width_for(header));
    }
}

fn find_header_column(worksheet: &mut umya_spreadsheet::Worksheet, header: &str, last_column: u32) -> Option<u32> {
    for column in 1..=last_column {
        if worksheet.value((column, 1)).trim().eq_ignore_ascii_case(header) {
            return Some(column);
        }
    }
    None
}

fn add_list_validation(worksheet: &mut umya_spreadsheet::Worksheet, header: &str, values: &[&str], last_column: u32) {
    let Some(column) = find_header_column(worksheet, header, last_column) else { return };
    let letter = column_letter(column);
    let formula = format!("\"{}\"", values.join(","));
    let mut validation = DataValidation::default();
    validation.set_type(DataValidationValues::List);
    validation.set_allow_blank(true);
    validation.set_formula1(formula);
    validation.set_show_error_message(true);
    validation.set_error_title("Choose a listed value");
    validation.set_error_message(format!("Allowed values: {}", values.join(", ")));
    validation.sequence_of_references_mut().set_sqref(format!("{letter}2:{letter}501"));
    let mut validations = DataValidations::default();
    validations.add_data_validation_list(validation);
    worksheet.set_data_validations(validations);
}

fn add_whole_number_validation(worksheet: &mut umya_spreadsheet::Worksheet, header: &str, minimum: u32, maximum: u32, last_column: u32) {
    let Some(column) = find_header_column(worksheet, header, last_column) else { return };
    let letter = column_letter(column);
    let mut validation = DataValidation::default();
    validation.set_type(DataValidationValues::Whole);
    validation.set_operator(DataValidationOperatorValues::Between);
    validation.set_allow_blank(true);
    validation.set_formula1(minimum.to_string());
    validation.set_formula2(maximum.to_string());
    validation.set_show_error_message(true);
    validation.set_error_title("Invalid number");
    validation.set_error_message(format!("Enter a whole number from {minimum} through {maximum}"));
    validation.sequence_of_references_mut().set_sqref(format!("{letter}2:{letter}501"));
    let mut validations = DataValidations::default();
    validations.add_data_validation_list(validation);
    worksheet.set_data_validations(validations);
}

fn tab_color(worksheet: &mut umya_spreadsheet::Worksheet, argb: &str) {
    worksheet.set_tab_color(header_color(argb));
}

fn create_instructions_sheet(book: &mut umya_spreadsheet::Workbook) {
    let worksheet = book.new_sheet("Instructions").expect("fresh workbook");
    tab_color(worksheet, "FF88C0D0");
    let headers: Vec<String> = vec!["Step".into(), "Topic".into(), "Instruction".into()];
    style_sheet(worksheet, &headers);
    worksheet.column_dimension_mut("A").set_width(6.0);
    worksheet.column_dimension_mut("B").set_width(25.0);
    worksheet.column_dimension_mut("C").set_width(112.0);
    let instructions: [(u32, &str, String); 10] = [
        (1, "Branches first", "Enter every location in Branches. Branch Code and Warehouse Code must each be unique. Branch Name, Branch Code, and Warehouse Code are required.".into()),
        (2, "Equipment sheets", "Use the dedicated Router, Switch, iLO, Server, NVR, AccessPoint, Scale, Client, Checkout, or POS sheet. Each sheet contains only fields available for that equipment type.".into()),
        (3, "Branch association", "Every equipment row requires Branch Code. It must exactly match a Branch Code in this workbook or an existing application branch.".into()),
        (4, "Required equipment fields", "Branch Code, Device Name, and IP are required on every equipment row. IP may be an IPv4 address or hostname.".into()),
        (5, "Dashboard", "Choose Show to monitor and display the equipment on Dashboard, or Hide to keep it only in the directory. Blank is treated as Hide.".into()),
        (6, "One Router", "Each branch can contain at most one Router. A Router row updates the existing Router for the same Branch Code.".into()),
        (7, "Switch ports", format!("The Switch sheet includes {MAX_SWITCH_PORTS} explicit port groups in each row. Define no more than {MAX_SWITCH_PORTS} unique Port Numbers from 1 through {MAX_SWITCH_PORTS}. Port Status options are Up, Down, or Disabled.")),
        (8, "Updates", "Router rows match by Branch Code. Other equipment rows match by Branch Code + equipment type + IP. Matching records are updated; other rows are added.".into()),
        (9, "Atomic import", "The workbook is validated before it changes data. If any row is invalid, nothing is imported and the reported rows must be corrected.".into()),
        (10, "Do not rename headers", "Keep worksheet names and row-1 column headings unchanged. Blank equipment sheets are valid and should remain in the workbook.".into()),
    ];
    for (row, (step, topic, instruction)) in instructions.iter().enumerate() {
        let row_number = row as u32 + 2;
        worksheet.cell_mut((1u32, row_number)).set_value(step.to_string());
        worksheet.cell_mut((2u32, row_number)).set_value(*topic);
        worksheet.cell_mut((3u32, row_number)).set_value(instruction.clone());
        worksheet.row_dimension_mut(row_number).set_height(38.0);
    }
}

fn create_branches_sheet(book: &mut umya_spreadsheet::Workbook) {
    let worksheet = book.new_sheet("Branches").expect("fresh workbook");
    tab_color(worksheet, "FFA3BE8C");
    let headers: Vec<String> = BRANCH_HEADERS.iter().map(|header| (*header).into()).collect();
    style_sheet(worksheet, &headers);
    let widths = [("A", 24.0), ("B", 18.0), ("C", 20.0), ("H", 22.0), ("I", 20.0), ("J", 22.0), ("K", 20.0)];
    for (letter, width) in widths {
        worksheet.column_dimension_mut(letter).set_width(width);
    }
}

fn create_equipment_sheet(book: &mut umya_spreadsheet::Workbook, type_name: &str) {
    let headers = device_sheet_headers(type_name);
    let worksheet = book.new_sheet(type_name).expect("fresh workbook");
    tab_color(worksheet, if type_name == "Switch" { "FFB48EAD" } else { "FF81A1C1" });
    let last_column = headers.len() as u32;
    style_sheet(worksheet, &headers);
    add_list_validation(worksheet, "Dashboard", &["Show", "Hide"], last_column);
    let port_groups = if type_name == "Switch" { MAX_SWITCH_PORTS } else { 0 };
    for group in 1..=port_groups {
        let status_header = switch_port_header(group, "Status");
        add_list_validation(worksheet, &status_header, &["Up", "Down", "Disabled"], last_column);
        let number_header = switch_port_header(group, "Number");
        add_whole_number_validation(worksheet, &number_header, 1, MAX_SWITCH_PORTS as u32, last_column);
    }
    if headers.iter().any(|header| header == "Port") {
        add_whole_number_validation(worksheet, "Port", 1, 65535, last_column);
    }
}

pub struct ExcelService<'a> {
    pub database: &'a AppDatabase,
}

impl<'a> ExcelService<'a> {
    pub fn new(database: &'a AppDatabase) -> Self {
        Self { database }
    }

    /// Builds `HyperFamily-Import-Template.xlsx`: Instructions + Branches +
    /// one sheet per equipment type with the same validation dropdowns.
    pub fn create_template(&self, output_path: &std::path::Path, actor: &str) -> AppResult<Value> {
        let mut book = umya_spreadsheet::new_file();
        // The fresh workbook ships with one default sheet — drop it once the
        // real sheets exist so the tab order matches the Electron build.
        create_instructions_sheet(&mut book);
        create_branches_sheet(&mut book);
        for type_name in DEVICE_TYPES {
            create_equipment_sheet(&mut book, type_name);
        }
        let _ = book.remove_sheet(0);
        umya_spreadsheet::writer::xlsx::write(&book, output_path)
            .map_err(|error| AppError::new(format!("The workbook could not be written: {error}")))?;
        self.database.audit(actor, "IMPORT_TEMPLATE_EXPORT", &output_path.to_string_lossy(), &format!("{} equipment sheets with {MAX_SWITCH_PORTS} Switch port groups", DEVICE_TYPES.len()));
        Ok(json_success(output_path))
    }

    /// Reads and validates a workbook WITHOUT touching the database.
    pub fn parse_import_workbook(&self, input_path: &std::path::Path) -> AppResult<Value> {
        let book = umya_spreadsheet::reader::xlsx::read(input_path)
            .map_err(|error| AppError::new(format!("The workbook could not be read: {error}")))?;
        let mut errors: Vec<String> = Vec::new();

        let legacy_layout = book.sheet_by_name("Devices").is_ok();
        let branch_headers: Vec<String> = (if legacy_layout { LEGACY_BRANCH_HEADERS } else { BRANCH_HEADERS })
            .iter()
            .map(|header| (*header).into())
            .collect();
        let branch_rows = read_sheet_rows(&book, "Branches", &branch_headers, true, &mut errors);

        let device_rows: Vec<SheetRow> = if legacy_layout {
            let headers: Vec<String> = LEGACY_DEVICE_HEADERS.iter().map(|header| (*header).into()).collect();
            read_sheet_rows(&book, "Devices", &headers, true, &mut errors)
        } else {
            let mut rows = Vec::new();
            for type_name in DEVICE_TYPES {
                let headers = device_sheet_headers(type_name);
                let typed_rows = read_sheet_rows(&book, type_name, &headers, true, &mut errors);
                for row in typed_rows {
                    let mut values = std::collections::HashMap::new();
                    values.insert("Branch Code".to_string(), row.values.get("Branch Code").cloned().unwrap_or_default());
                    values.insert("Device Type".to_string(), (*type_name).to_string());
                    values.insert("Dashboard".to_string(), row.values.get("Dashboard").cloned().unwrap_or_default());
                    for (header, canonical) in sheet_fields(type_name) {
                        values.insert((*canonical).to_string(), row.values.get(*header).cloned().unwrap_or_default());
                    }
                    rows.push(SheetRow {
                        row_number: row.row_number,
                        sheet_name: row.sheet_name.clone(),
                        values,
                        typed_values: row.values.clone(),
                    });
                }
            }
            rows
        };
        let port_rows = if legacy_layout && book.sheet_by_name("Switch Ports").is_ok() {
            let headers: Vec<String> = PORT_HEADERS.iter().map(|header| (*header).into()).collect();
            read_sheet_rows(&book, "Switch Ports", &headers, true, &mut errors)
        } else {
            Vec::new()
        };

        if branch_rows.is_empty() && device_rows.is_empty() {
            errors.push("The workbook does not contain any populated Branch or equipment rows".into());
        }

        let mut branches: Vec<Value> = Vec::new();
        let mut branch_codes: std::collections::HashSet<String> = Default::default();
        let mut warehouse_codes: std::collections::HashSet<String> = Default::default();
        for row in &branch_rows {
            let row_label = format!("Branches row {}", row.row_number);
            let branch_name = row.field2("Branch Name", "Name");
            let code = row.field2("Branch Code", "Code");
            let warehouse_code = row.field("Warehouse Code");
            if branch_name.is_empty() {
                errors.push(format!("{row_label}: Branch Name is required"));
            }
            if code.is_empty() {
                errors.push(format!("{row_label}: Branch Code is required"));
            } else {
                let pattern = regex::Regex::new(r"^[A-Za-z0-9_-]{2,20}$").expect("static regex");
                if !pattern.is_match(&code) {
                    errors.push(format!("{row_label}: Branch Code must use 2-20 letters, numbers, dashes, or underscores"));
                }
            }
            if warehouse_code.is_empty() {
                errors.push(format!("{row_label}: Warehouse Code is required"));
            } else {
                let pattern = regex::Regex::new(r"^[A-Za-z0-9_-]{1,40}$").expect("static regex");
                if !pattern.is_match(&warehouse_code) {
                    errors.push(format!("{row_label}: Warehouse Code must use up to 40 letters, numbers, dashes, or underscores"));
                }
            }
            let code_key = code.to_lowercase();
            let warehouse_key = warehouse_code.to_lowercase();
            if !code.is_empty() && branch_codes.contains(&code_key) {
                errors.push(format!("{row_label}: Branch Code \u{201c}{code}\u{201d} is duplicated in this workbook"));
            }
            if !warehouse_code.is_empty() && warehouse_codes.contains(&warehouse_key) {
                errors.push(format!("{row_label}: Warehouse Code \u{201c}{warehouse_code}\u{201d} is duplicated in this workbook"));
            }
            if !code.is_empty() {
                branch_codes.insert(code_key);
            }
            if !warehouse_code.is_empty() {
                warehouse_codes.insert(warehouse_key);
            }
            for header in ["IP Link1", "IP Link2"] {
                let value = row.field(header);
                if !value.is_empty() && !is_valid_host(&value) {
                    errors.push(format!("{row_label}: {header} is invalid"));
                }
            }
            branches.push(serde_json::json!({
                "name": branch_name, "code": code, "warehouse_code": warehouse_code,
                "link1": row.field("Link1"), "ip_link1": row.field("IP Link1"),
                "link2": row.field("Link2"), "ip_link2": row.field("IP Link2"),
                "manager_name": row.field("Manager Name"), "manager_tell": row.field("Manager Tell"),
                "deputy_name": row.field("Deputy Name"), "deputy_tell": row.field("Deputy Tell")
            }));
        }

        let mut devices: Vec<Value> = Vec::new();
        let mut device_keys: std::collections::HashSet<String> = Default::default();
        let mut router_branches: std::collections::HashSet<String> = Default::default();
        for row in &device_rows {
            let row_label = format!("{} row {}", row.sheet_name, row.row_number);
            let device_type = row.field("Device Type");
            let branch_code = row.field("Branch Code");
            let device_name = row.field("Device Name");
            let ip = row.field("IP");
            if branch_code.is_empty() {
                errors.push(format!("{row_label}: Branch Code is required"));
            }
            if !DEVICE_TYPES.contains(&device_type.as_str()) {
                errors.push(format!("{row_label}: Device Type must be one of {}", DEVICE_TYPES.join(", ")));
            }
            if device_name.is_empty() {
                errors.push(format!("{row_label}: Device Name is required"));
            }
            if ip.is_empty() || !is_valid_host(&ip) {
                errors.push(format!("{row_label}: IP must be a valid IPv4 address or hostname"));
            }
            if device_type == "Router" && !branch_code.is_empty() {
                let router_key = branch_code.to_lowercase();
                if router_branches.contains(&router_key) {
                    errors.push(format!("{row_label}: only one Router can be defined for Branch Code \u{201c}{branch_code}\u{201d}"));
                }
                router_branches.insert(router_key);
            }
            let device_key = if device_type == "Router" {
                format!("{}::router", branch_code.to_lowercase())
            } else {
                format!("{}::{}::{}", branch_code.to_lowercase(), device_type.to_lowercase(), ip.to_lowercase())
            };
            if !branch_code.is_empty() && !device_type.is_empty() && !ip.is_empty() && device_keys.contains(&device_key) {
                errors.push(format!("{row_label}: this device is duplicated in the workbook"));
            }
            if !branch_code.is_empty() && !device_type.is_empty() && !ip.is_empty() {
                device_keys.insert(device_key);
            }

            let mut device = serde_json::json!({
                "branch_code": branch_code,
                "device_type": device_type,
                "is_dashboard_visible": parse_dashboard(&row.field("Dashboard"), &row_label, &mut errors),
                "switch_ports": []
            });
            for (header, key) in FIELD_MAP {
                let value = row.field(header);
                device[*key] = if value.is_empty() { Value::Null } else { Value::String(value.clone()) };
            }
            let port_text = row.field("Port");
            if !port_text.is_empty() {
                match port_text.parse::<i64>() {
                    Ok(port) if (1..=65535).contains(&port) => device["port"] = Value::from(port),
                    _ => errors.push(format!("{row_label}: Port must be a whole number from 1 through 65535")),
                }
            }
            let checkout_text = row.field("Checkout Number");
            if !checkout_text.is_empty() {
                match checkout_text.parse::<i64>() {
                    Ok(checkout) if checkout >= 1 => device["checkout_number"] = Value::from(checkout),
                    _ => errors.push(format!("{row_label}: Checkout Number must be a positive whole number")),
                }
            }
            if device_type == "Switch" && !legacy_layout {
                device["switch_ports"] = parse_typed_switch_ports(row, &row_label, &mut errors);
            }
            devices.push(device);
        }

        if legacy_layout {
            // Attach Switch Ports rows to their devices, same as the legacy parser.
            let mut switch_index: std::collections::HashMap<String, usize> = Default::default();
            for (index, device) in devices.iter().enumerate() {
                if device.get("device_type").and_then(Value::as_str) == Some("Switch") {
                    let key = format!(
                        "{}::{}",
                        device.get("branch_code").and_then(Value::as_str).unwrap_or("").to_lowercase(),
                        device.get("ip").and_then(Value::as_str).unwrap_or("").to_lowercase()
                    );
                    switch_index.insert(key, index);
                }
            }
            let mut seen_ports: std::collections::HashMap<String, std::collections::HashSet<i64>> = Default::default();
            for row in &port_rows {
                let row_label = format!("Switch Ports row {}", row.row_number);
                let key = format!("{}::{}", row.field("Branch Code").to_lowercase(), row.field("Device IP").to_lowercase());
                let Some(&index) = switch_index.get(&key) else {
                    errors.push(format!(
                        "{row_label}: no Switch row matches Branch Code \u{201c}{}\u{201d} and Device IP \u{201c}{}\u{201d}",
                        row.field("Branch Code"),
                        row.field("Device IP")
                    ));
                    continue;
                };
                let port_count = devices[index].get("switch_ports").and_then(Value::as_array).map(Vec::len).unwrap_or(0);
                if port_count >= MAX_SWITCH_PORTS {
                    errors.push(format!("{row_label}: a Switch can contain at most {MAX_SWITCH_PORTS} ports"));
                    continue;
                }
                let port = parse_switch_port_values(
                    &row.field("Port Number"),
                    &row.field("VLAN"),
                    &row.field("Status"),
                    &row.field("IP"),
                    &row.field("Details"),
                    &row_label,
                    &mut errors,
                );
                let Some(port) = port else { continue };
                let entry = seen_ports.entry(key).or_default();
                if entry.contains(&port.port_number) {
                    errors.push(format!("{row_label}: Switch Port Number {} is duplicated for this Switch", port.port_number));
                } else {
                    entry.insert(port.port_number);
                    devices[index]["switch_ports"].as_array_mut().expect("array").push(port.to_value());
                }
            }
        }

        if !errors.is_empty() {
            let mut report: Vec<String> = errors.iter().take(30).cloned().collect();
            let extra = errors.len() - report.len();
            if extra > 0 {
                report.push(format!("\u{2026}and {extra} more errors"));
            }
            return Err(AppError::new(format!("Excel import validation failed:\n\u{2022} {}", report.join("\n\u{2022} "))));
        }
        Ok(serde_json::json!({
            "branches": branches,
            "devices": devices,
            "layout": if legacy_layout { "legacy" } else { "type-specific" }
        }))
    }

    /// Validates then imports through the database transaction (atomic).
    pub fn import_directory(&self, input_path: &std::path::Path, actor: &str) -> AppResult<Value> {
        let payload = self.parse_import_workbook(input_path)?;
        let result = self.database.import_directory(&payload, actor)?;
        Ok(serde_json::json!({
            "success": true,
            "path": input_path.to_string_lossy(),
            "layout": payload.get("layout").cloned().unwrap_or(Value::Null),
            "branches_added": result.get("branches_added").cloned().unwrap_or(json!(0)),
            "branches_updated": result.get("branches_updated").cloned().unwrap_or(json!(0)),
            "devices_added": result.get("devices_added").cloned().unwrap_or(json!(0)),
            "devices_updated": result.get("devices_updated").cloned().unwrap_or(json!(0)),
            "switch_ports_imported": result.get("switch_ports_imported").cloned().unwrap_or(json!(0))
        }))
    }

    /// Inventory export: filtered rows, zebra stripes, filter row, same columns.
    pub fn export_inventory(&self, filters: &Value, output_path: &std::path::Path) -> AppResult<Value> {
        let all_rows = self.database.list_inventory()?;
        let branch = filters.get("branch").and_then(Value::as_str).unwrap_or("all");
        let device_type = filters.get("type").and_then(Value::as_str).unwrap_or("all");
        let query = filters.get("query").and_then(Value::as_str).unwrap_or("");
        let mut rows: Vec<&Value> = Vec::new();
        for row in &all_rows {
            if branch != "all" {
                let branch_id = row.get("branch_id").map(branch_id_key);
                if branch_id.as_deref() != Some(branch) {
                    continue;
                }
            }
            if device_type != "all" && row.get("device_type").and_then(Value::as_str) != Some(device_type) {
                continue;
            }
            if !query.is_empty() && !matches_query(row, query) {
                continue;
            }
            rows.push(row);
        }

        let columns: [(&str, &str, f64); 26] = [
            ("branch_name", "Branch", 22.0),
            ("branch_code", "Branch Code", 15.0),
            ("branch_warehouse_code", "Warehouse Code", 18.0),
            ("device_type", "Device Type", 17.0),
            ("model", "Model", 24.0),
            ("name", "Name", 24.0),
            ("hostname", "Hostname", 22.0),
            ("ip", "IP", 17.0),
            ("port", "Port", 10.0),
            ("location", "Location", 22.0),
            ("asset_code", "Asset Code", 20.0),
            ("serial_number", "Serial Number", 22.0),
            ("connection_type", "Connection Type", 18.0),
            ("connection_port", "Connection Port", 18.0),
            ("esxi_version", "ESXI Version", 16.0),
            ("version", "Software Version", 18.0),
            ("user", "User", 20.0),
            ("domain", "Domain", 18.0),
            ("checkout_number", "Checkout Number", 17.0),
            ("brand", "Brand", 18.0),
            ("terminal_id", "Terminal ID", 18.0),
            ("acceptance_id", "Acceptance ID", 18.0),
            ("switch_ports_summary", "Switch Ports", 48.0),
            ("dashboard_visibility", "Dashboard", 13.0),
            ("status", "Status", 12.0),
            ("ping_time", "Last Ping (ms)", 15.0),
        ];

        let mut book = umya_spreadsheet::new_file();
        {
            let worksheet = book.sheet_mut(0).expect("fresh workbook");
            let _ = worksheet.set_name("Inventory");
            for (index, (_, header, width)) in columns.iter().enumerate() {
                let letter = column_letter(index as u32 + 1);
                let cell = worksheet.cell_mut(format!("{letter}1").as_str());
                cell.set_value(*header);
                let mut style = Style::default();
                style.font_mut().set_bold(true);
                style.font_mut().set_color(header_color("FFFFFFFF"));
                let pattern: &mut PatternFill = style.fill_mut().pattern_fill_mut();
                pattern.set_pattern_type(PatternValues::Solid);
                pattern.set_foreground_color(header_color("FF5E81AC"));
                let mut alignment = Alignment::default();
                alignment.set_vertical(VerticalAlignmentValues::Center);
                style.set_alignment(alignment);
                cell.set_style(style);
                worksheet.column_dimension_mut(&letter).set_width(*width);
            }
            let last_column = column_letter(columns.len() as u32);
            let last_row = rows.len() as u32 + 1;
            worksheet.set_auto_filter(format!("A1:{last_column}{last_row}"));
            for (row_index, row) in rows.iter().enumerate() {
                let row_number = row_index as u32 + 2;
                for (index, (key, _, _)) in columns.iter().enumerate() {
                    let value: String = match *key {
                        "switch_ports_summary" => format_switch_ports(row.get("switch_ports").and_then(Value::as_array)),
                        "dashboard_visibility" => (if row.get("is_dashboard_visible").and_then(Value::as_bool).unwrap_or(false) { "Shown" } else { "Hidden" }).into(),
                        "status" => row.get("status").and_then(Value::as_str).unwrap_or("").into(),
                        "ping_time" => row
                            .get("ping_time")
                            .map(|value| match value {
                                Value::Number(number) => number.to_string(),
                                Value::String(text) => text.clone(),
                                Value::Null => String::new(),
                                other => other.to_string(),
                            })
                            .unwrap_or_default(),
                        other => row.get(other).map(cell_text).unwrap_or_default(),
                    };
                    if value.is_empty() {
                        continue;
                    }
                    let coordinate = format!("{}{row_number}", column_letter(index as u32 + 1));
                    let cell = worksheet.cell_mut(coordinate.as_str());
                    cell.set_value(value);
                    let mut style = Style::default();
                    let mut alignment = Alignment::default();
                    alignment.set_vertical(VerticalAlignmentValues::Top);
                    alignment.set_wrap_text(true);
                    style.set_alignment(alignment);
                    if row_number % 2 == 0 {
                        let pattern: &mut PatternFill = style.fill_mut().pattern_fill_mut();
                        pattern.set_pattern_type(PatternValues::Solid);
                        pattern.set_foreground_color(header_color("FFF4F6FA"));
                    }
                    cell.set_style(style);
                }
            }
        }
        umya_spreadsheet::writer::xlsx::write(&book, output_path)
            .map_err(|error| AppError::new(format!("The workbook could not be written: {error}")))?;
        self.database.audit("Admin", "INVENTORY_EXPORT", &output_path.to_string_lossy(), &format!("{} devices exported", rows.len()));
        Ok(serde_json::json!({ "success": true, "path": output_path.to_string_lossy(), "count": rows.len() }))
    }
}

fn json_success(path: &std::path::Path) -> Value {
    serde_json::json!({ "success": true, "path": path.to_string_lossy() })
}

fn branch_id_key(value: &Value) -> String {
    match value {
        Value::Number(number) => number.to_string(),
        Value::String(text) => text.clone(),
        other => other.to_string(),
    }
}

fn cell_text(value: &Value) -> String {
    match value {
        Value::Null => String::new(),
        Value::String(text) => text.clone(),
        Value::Bool(flag) => flag.to_string(),
        other => other.to_string(),
    }
}

fn is_valid_host(value: &str) -> bool {
    if value.is_empty() || value.len() > 253 {
        return false;
    }
    if value.starts_with('-') {
        return false;
    }
    // Same accept set as the original look-ahead pattern: dot-separated
    // labels, each 1-63 letters/digits/hyphens, no empty labels, no leading
    // hyphen, no trailing dot.
    let hostname = regex::Regex::new(r"^[A-Za-z0-9-]{1,63}(\.[A-Za-z0-9-]{1,63})*$").expect("static regex");
    if hostname.is_match(value) {
        return true;
    }
    let parts: Vec<&str> = value.split('.').collect();
    parts.len() == 4
        && parts
            .iter()
            .all(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()) && part.parse::<u32>().map(|number| number <= 255).unwrap_or(false))
}

struct ParsedPort {
    port_number: i64,
    value: Value,
}

impl ParsedPort {
    fn to_value(&self) -> Value {
        self.value.clone()
    }
}

fn parse_switch_port_values(
    number_text: &str,
    vlan: &str,
    status: &str,
    ip: &str,
    details: &str,
    row_label: &str,
    errors: &mut Vec<String>,
) -> Option<ParsedPort> {
    let populated = ![number_text, vlan, status, ip, details].iter().all(|value| value.is_empty());
    if !populated {
        return None;
    }
    let port_number = match number_text.trim().parse::<i64>() {
        Ok(number) if (1..=MAX_SWITCH_PORTS as i64).contains(&number) => number,
        _ => {
            errors.push(format!("{row_label}: Switch Port Number must be a whole number from 1 through {MAX_SWITCH_PORTS}"));
            return None;
        }
    };
    let status_value = if status.is_empty() { "Up".to_string() } else { status.to_string() };
    let normalized = status_value.to_lowercase();
    if !["up", "down", "disabled"].contains(&normalized.as_str()) {
        errors.push(format!("{row_label}: Switch port {port_number} Status must be Up, Down, or Disabled"));
    }
    if !ip.is_empty() && !is_valid_host(ip) {
        errors.push(format!("{row_label}: Switch port {port_number} IP is invalid"));
    }
    Some(ParsedPort {
        port_number,
        value: serde_json::json!({
            "port_number": port_number,
            "vlan": if vlan.is_empty() { Value::Null } else { Value::String(vlan.into()) },
            "status": if ["up", "down", "disabled"].contains(&normalized.as_str()) { normalized } else { "up".into() },
            "ip": if ip.is_empty() { Value::Null } else { Value::String(ip.into()) },
            "details": if details.is_empty() { Value::Null } else { Value::String(details.into()) }
        }),
    })
}

fn parse_typed_switch_ports(row: &SheetRow, row_label: &str, errors: &mut Vec<String>) -> Value {
    let mut ports = Vec::new();
    let mut seen: std::collections::HashSet<i64> = Default::default();
    for group in 1..=MAX_SWITCH_PORTS {
        let port = parse_switch_port_values(
            &row.typed_field(&switch_port_header(group, "Number")),
            &row.typed_field(&switch_port_header(group, "VLAN")),
            &row.typed_field(&switch_port_header(group, "Status")),
            &row.typed_field(&switch_port_header(group, "IP")),
            &row.typed_field(&switch_port_header(group, "Details")),
            &format!("{row_label}, port group {group}"),
            errors,
        );
        let Some(port) = port else { continue };
        if seen.contains(&port.port_number) {
            errors.push(format!("{row_label}: Switch Port Number {} is duplicated", port.port_number));
        } else {
            seen.insert(port.port_number);
            ports.push(port.to_value());
        }
    }
    Value::Array(ports)
}

fn parse_dashboard(value: &str, row_label: &str, errors: &mut Vec<String>) -> i64 {
    if value.is_empty() {
        return 0;
    }
    match value.to_lowercase().as_str() {
        "show" | "yes" | "true" | "1" => 1,
        "hide" | "no" | "false" | "0" => 0,
        _ => {
            errors.push(format!("{row_label}: Dashboard must be Show or Hide"));
            0
        }
    }
}

struct SheetRow {
    row_number: u32,
    sheet_name: String,
    values: std::collections::HashMap<String, String>,
    typed_values: std::collections::HashMap<String, String>,
}

impl SheetRow {
    fn field(&self, header: &str) -> String {
        self.values.get(header).cloned().unwrap_or_default()
    }

    fn field2(&self, header_a: &str, header_b: &str) -> String {
        let value = self.field(header_a);
        if value.is_empty() {
            self.field(header_b)
        } else {
            value
        }
    }

    fn typed_field(&self, header: &str) -> String {
        self.typed_values.get(header).cloned().unwrap_or_default()
    }
}

/// Reads a worksheet into labelled rows: header row maps column → name, then
/// every populated row becomes `{ rowNumber, values, sheetName }`.
fn read_sheet_rows(
    book: &umya_spreadsheet::Workbook,
    sheet_name: &str,
    required_headers: &[String],
    required: bool,
    errors: &mut Vec<String>,
) -> Vec<SheetRow> {
    let Ok(worksheet) = book.sheet_by_name(sheet_name) else {
        if required {
            errors.push(format!("Missing required worksheet \u{201c}{sheet_name}\u{201d}"));
        }
        return Vec::new();
    };
    let (highest_column, highest_row) = worksheet.highest_column_and_row();
    // Header index: lowercase header → column number (first one wins).
    let mut indexes: std::collections::HashMap<String, u32> = Default::default();
    for column in 1..=highest_column {
        let header = worksheet.value((column, 1)).trim().to_lowercase();
        if !header.is_empty() && !indexes.contains_key(&header) {
            indexes.insert(header, column);
        }
    }
    let mut missing: Vec<&str> = Vec::new();
    for header in required_headers {
        if !indexes.contains_key(&header.to_lowercase()) {
            missing.push(header);
        }
    }
    if !missing.is_empty() {
        errors.push(format!("{sheet_name}: missing column \u{201c}{}\u{201d}", missing.join("\u{201c}, \u{201c}")));
        return Vec::new();
    }
    let mut rows = Vec::new();
    for row_number in 2..=highest_row {
        let mut values: std::collections::HashMap<String, String> = Default::default();
        let mut populated = false;
        for header in required_headers {
            let column = indexes[&header.to_lowercase()];
            let value = worksheet.value((column, row_number)).trim().to_string();
            if !value.is_empty() {
                populated = true;
            }
            values.insert(header.clone(), value);
        }
        if populated {
            rows.push(SheetRow {
                row_number,
                sheet_name: sheet_name.to_string(),
                values,
                typed_values: Default::default(),
            });
        }
    }
    rows
}

fn matches_query(device: &Value, query: &str) -> bool {
    let needle = query.to_lowercase();
    if needle.is_empty() {
        return true;
    }
    let mut values: Vec<String> = Vec::new();
    for key in [
        "name", "hostname", "ip", "port", "model", "asset_code", "serial_number", "location", "connection_type", "connection_port",
        "esxi_version", "version", "user", "domain", "checkout_number", "brand", "terminal_id", "acceptance_id",
        "branch_name", "branch_code", "branch_warehouse_code",
    ] {
        values.push(device.get(key).map(cell_text).unwrap_or_default());
    }
    if let Some(ports) = device.get("switch_ports").and_then(Value::as_array) {
        for port in ports {
            for key in ["port_number", "vlan", "status", "ip", "details"] {
                values.push(port.get(key).map(cell_text).unwrap_or_default());
            }
        }
    }
    values.iter().any(|value| value.to_lowercase().contains(&needle))
}

fn format_switch_ports(ports: Option<&Vec<Value>>) -> String {
    let Some(ports) = ports else { return String::new() };
    ports
        .iter()
        .map(|port| {
            let mut details: Vec<String> = vec![format!("Port {}", port.get("port_number").map(cell_text).unwrap_or_default())];
            let vlan = port.get("vlan").map(cell_text).unwrap_or_default();
            if !vlan.is_empty() {
                details.push(format!("VLAN {vlan}"));
            }
            let status = port.get("status").map(cell_text).unwrap_or_default();
            if !status.is_empty() {
                details.push(status);
            }
            let ip = port.get("ip").map(cell_text).unwrap_or_default();
            if !ip.is_empty() {
                details.push(ip);
            }
            let note = port.get("details").map(cell_text).unwrap_or_default();
            if !note.is_empty() {
                details.push(note);
            }
            details.join(" \u{00b7} ")
        })
        .collect::<Vec<_>>()
        .join("; ")
}
